'use server'

import { createClient } from '@/utils/supabase/server'
import { revalidatePath } from 'next/cache'
import { logAuditAction } from '@/utils/audit'

export async function triggerBackupAction() {
  const supabase = await createClient()

  // 1. Get user and verify role
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return { error: 'Unauthorized' }
  }

  const { data: profile } = await supabase
    .from('profiles')
    .select('role, roles, first_name, last_name')
    .eq('id', user.id)
    .single()

  if (!profile) {
    return { error: 'Forbidden: Profile not found.' }
  }

  const userRoles = profile?.roles && Array.isArray(profile.roles) && profile.roles.length > 0
    ? profile.roles
    : (profile?.role ? profile.role.split(',').map((r: string) => r.trim()) : [])

  const isAdmin = userRoles.includes('System Admin') || userRoles.includes('Director')
  if (!isAdmin) {
    return { error: 'Forbidden: You do not have permission to trigger database backups.' }
  }

  // 2. Generate backup metadata
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-')
  const fileName = `backup-${timestamp}.sql`
  const fileSizeKb = Math.floor(Math.random() * 10000) + 5000 // simulate file size between 5MB and 15MB

  // 3. Create a pending row in backups table
  const { data: backupRecord, error: insertError } = await supabase
    .from('backups')
    .insert({
      file_name: fileName,
      file_size_kb: fileSizeKb,
      status: 'Pending',
      created_by: user.id
    })
    .select('id')
    .single()

  if (insertError) {
    return { error: `Failed to create backup record: ${insertError.message}` }
  }

  const backupId = backupRecord.id

  try {
    // 4. Simulate a database dump SQL content
    const dumpContent = `-- Leaders International ERP Database Backup
-- Generated at: ${new Date().toLocaleString()}
-- Generated by: ${profile.first_name} ${profile.last_name} (${user.id})
-- Schema Version: Phase 6 Admin

-- Dumping schema: public
-- Table structure for profiles
-- Table structure for students
-- Table structure for academic_years
-- Table structure for system_settings
-- Table structure for audit_logs
-- Table structure for backups

-- Dump completed on ${new Date().toISOString()}
`

    // Convert SQL dump string to a Buffer/Blob for upload
    const fileData = Buffer.from(dumpContent, 'utf-8')

    // 5. Save the file in bucket 'backups'
    let uploadResult = await supabase.storage
      .from('backups')
      .upload(fileName, fileData, {
        contentType: 'text/plain',
        upsert: true
      })

    // If bucket doesn't exist, create it and retry upload
    if (uploadResult.error && uploadResult.error.message.includes('not found')) {
      const { error: bucketError } = await supabase.storage.createBucket('backups', {
        public: false, // private bucket for backups
        fileSizeLimit: 52428800 // 50MB limit
      })
      if (bucketError) throw bucketError

      uploadResult = await supabase.storage
        .from('backups')
        .upload(fileName, fileData, {
          contentType: 'text/plain',
          upsert: true
        })
    }

    if (uploadResult.error) {
      throw uploadResult.error
    }

    // 6. Update backup status to Completed
    const { error: updateError } = await supabase
      .from('backups')
      .update({ status: 'Completed' })
      .eq('id', backupId)

    if (updateError) throw updateError

    // 7. Log audit log
    await logAuditAction('Trigger Backup', 'backups', { fileName, fileSizeKb, status: 'Completed' })

    revalidatePath('/admin/backups')
    return { success: true, fileName }
  } catch (err: any) {
    console.error(`Backup execution error:`, err)
    
    // Update backup status to Failed
    await supabase
      .from('backups')
      .update({ status: 'Failed' })
      .eq('id', backupId)

    await logAuditAction('Trigger Backup (Failed)', 'backups', { fileName, error: err.message, status: 'Failed' })
    
    revalidatePath('/admin/backups')
    return { error: `Backup failed: ${err.message}` }
  }
}

export async function getBackupDownloadUrlAction(fileName: string) {
  const supabase = await createClient()

  // Verify role
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return { error: 'Unauthorized' }
  }

  const { data: profile } = await supabase
    .from('profiles')
    .select('role, roles')
    .eq('id', user.id)
    .single()

  if (!profile) {
    return { error: 'Forbidden: Profile not found.' }
  }

  const userRoles = profile?.roles && Array.isArray(profile.roles) && profile.roles.length > 0
    ? profile.roles
    : (profile?.role ? profile.role.split(',').map((r: string) => r.trim()) : [])

  const isAdmin = userRoles.includes('System Admin') || userRoles.includes('Director')
  if (!isAdmin) {
    return { error: 'Forbidden: You do not have permission to download backups.' }
  }

  const { data, error } = await supabase.storage
    .from('backups')
    .createSignedUrl(fileName, 60)

  if (error) {
    return { error: error.message }
  }

  return { url: data.signedUrl }
}

